// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bIZr4hradD87HQvOoM1EO9_mbXsUfOM',
    appId: '1:396543864469:web:647c73a91c2e12e030759c',
    messagingSenderId: '396543864469',
    projectId: 'banco-pichincha-ec',
    authDomain: 'banco-pichincha-ec.firebaseapp.com',
    storageBucket: 'banco-pichincha-ec.firebasestorage.app',
    measurementId: 'G-PRRSYXJ60Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlSTNiI3SmKwm93VKjZ0H7Yr-AWnKzSA',
    appId: '1:396543864469:android:2c9ed0525b872caf30759c',
    messagingSenderId: '396543864469',
    projectId: 'banco-pichincha-ec',
    storageBucket: 'banco-pichincha-ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9Jo85qBXKgXRL46EJsiZ8N-3Ti_y9W8',
    appId: '1:396543864469:ios:07f580508b4dc35530759c',
    messagingSenderId: '396543864469',
    projectId: 'banco-pichincha-ec',
    storageBucket: 'banco-pichincha-ec.firebasestorage.app',
    iosBundleId: 'com.example.bcopichincha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe9Jo85qBXKgXRL46EJsiZ8N-3Ti_y9W8',
    appId: '1:396543864469:ios:07f580508b4dc35530759c',
    messagingSenderId: '396543864469',
    projectId: 'banco-pichincha-ec',
    storageBucket: 'banco-pichincha-ec.firebasestorage.app',
    iosBundleId: 'com.example.bcopichincha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2bIZr4hradD87HQvOoM1EO9_mbXsUfOM',
    appId: '1:396543864469:web:08000959c5f6e6a530759c',
    messagingSenderId: '396543864469',
    projectId: 'banco-pichincha-ec',
    authDomain: 'banco-pichincha-ec.firebaseapp.com',
    storageBucket: 'banco-pichincha-ec.firebasestorage.app',
    measurementId: 'G-SCH20HXW8R',
  );
}
